window.doorCards = [
  { type: "task", en: "Do 12 push-ups right now.", hi: "अभी 12 पुश-अप्स करें।" },
  { type: "task", en: "Drink a glass of water in one go. Your body is 60% water — this is the cheapest way to change it.", hi: "एक गिलास पानी एक ही बार में पिएं। शरीर 60% पानी से बना है — यह उसे बदलने का सबसे सस्ता तरीका है।" },
  { type: "task", en: "Take a long breath, hold it for two seconds, then let it go. Thank the universe for letting you experience this body, breath, joy, and sorrow.", hi: "एक लंबी सांस लें, दो सेकंड रोकें, फिर छोड़ें। और ब्रह्मांड को धन्यवाद कहें — इस शरीर, सांस और सुख-दुख का अनुभव कराने के लिए।" },
  { type: "task", en: "Compliment a parent, friend, or sibling for something they do every day that nobody notices.", hi: "माता-पिता, दोस्त या भाई-बहन में से किसी एक की तारीफ करें — उन कामों के लिए जो वे रोज़ करते हैं पर कोई ध्यान नहीं देता।" },
  { type: "task", en: "Clean your desk, table, or bed. Outer clutter feeds inner clutter.", hi: "अपना डेस्क, टेबल या बिस्तर साफ करें। बाहरी अव्यवस्था भीतरी अव्यवस्था को खुराक देती है।" },
  { type: "task", en: "Remove three things from your room that are no longer useful. Even tiny things count.", hi: "कमरे से 3 ऐसी चीज़ें बाहर करें जो अब किसी काम की नहीं। छोटा से छोटा सामान भी हो सकता है।" },
  { type: "phenomenon", en: "Voyager 1 is now about 24 billion kilometres away and still carries a message from humanity. Some work is not for results, but for bearing witness.", hi: "वॉयेजर-1 अब 24 अरब किलोमीटर दूर है और अब भी इंसानियत का संदेश लेकर चल रहा है। कुछ काम नतीजे के लिए नहीं, गवाही के लिए होते हैं।" },
  { type: "thought", en: "Are you good because you are good, or because someone is watching?", hi: "आप इसलिए अच्छे हैं क्योंकि आप अच्छे हैं, या इसलिए कि कोई देख रहा है?" },
  { type: "thought", en: "Does death frighten you, or the thought that you have not really lived?", hi: "मौत आपको डराती है, या यह विचार कि आप ठीक से जिए ही नहीं?" },
  { type: "thought", en: "If you discovered that you and your entire life were inside a simulation, would your pain become any less real?", hi: "अगर आपको पता चले कि आप और आपका पूरा जीवन किसी सिमुलेशन में है, तो क्या आपका दर्द कम असली हो जाएगा?" },
  { type: "thought", en: "What do you regret more: what you did, or what you never even started?", hi: "आपको किस बात का अफसोस है — जो किया, या जो कभी शुरू ही नहीं किया?" },
  { type: "task", en: "Sit in sunlight for 10 minutes. It is not just vitamin D; it is medicine for sleep and mood.", hi: "10 मिनट सूरज की रोशनी में बैठें। यह सिर्फ विटामिन नहीं, नींद और मूड की दवा है।" },
  { type: "task", en: "Go to sleep 20 minutes earlier today. Sleep is when the brain cleans itself.", hi: "आज 20 मिनट पहले सोएं। नींद वह समय है जब दिमाग खुद की सफाई करता है।" },
  { type: "task", en: "Put your phone aside 30 minutes before bed tonight.", hi: "आज सोने से 30 मिनट पहले फोन को साइड में रख दें।" },
  { type: "task", en: "Call one person for no reason other than to ask how they are.", hi: "किसी एक इंसान को बिना किसी काम से फोन करें, सिर्फ हाल पूछने के लिए।" },
  { type: "task", en: "Spend 15 minutes on the thing you have been postponing for weeks. Starting is the heaviest part.", hi: "15 मिनट वह काम करें जिसे आप हफ्तों से टाल रहे हैं। शुरुआत सबसे भारी हिस्सा होती है।" },
  { type: "task", en: "Look at your feet and thank them for 10 seconds. They carried you everywhere today.", hi: "अपने पैरों की तरफ देखें और 10 सेकंड धन्यवाद कहें — उन्होंने आज आपको हर जगह पहुंचाया।" },
  { type: "task", en: "Close your eyes for two minutes and count your breaths from 1 to 20. If your mind wanders, start again.", hi: "2 मिनट आंखें बंद करके सांस गिनें — 1 से 20 तक। मन भागे तो शुरू से।" },
  { type: "task", en: "Drop one thing you do every day without thinking — sugar, scrolling, or complaining.", hi: "एक ऐसी चीज़ आज छोड़ें जो आप बिना सोचे रोज़ करते हैं — चीनी, स्क्रॉल, या शिकायत।" },
  { type: "thought", en: "Take a photo of your room and ask what it says about you.", hi: "अपने कमरे की एक तस्वीर लें और देखें कि वह आपके बारे में क्या कहती है।" },
  { type: "thought", en: "Forgive the person who hurt you — at least inside yourself. The one carrying the weight is the one who gets tired.", hi: "उस इंसान को माफ करें जिसने चोट पहुंचाई — कम से कम अपने भीतर। बोझ उठाने वाला ही थकता है।" },
  { type: "task", en: "Try box breathing: inhale for four, hold for four, exhale for four, hold for four. Your breath can persuade your mind to calm down.", hi: "4-4-4-4 की सांस लें — चार गिनें, रोकें, छोड़ें, रोकें। दिमाग शांत होता है क्योंकि सांस उसे राज़ी करती है।" },
  { type: "task", en: "Spend 10 minutes doing something you love — music, reading, making. Happiness needs practice too.", hi: "अपनी पसंद की एक चीज़ 10 मिनट करें — संगीत, पढ़ना, बनाना। खुशी भी अभ्यास मांगती है।" },
  { type: "task", en: "If you can, water a plant today. Giving life is one way of living.", hi: "मुमकिन हो तो आज किसी पौधे को पानी दें। जीवन देना भी जीवन जीने का एक तरीका है।" },
  { type: "task", en: "Be bored for one full hour today. Step outside your thoughts and notice what is near you. Do not touch your phone.", hi: "आज आपको एक घंटा बोर होना है। अपनी सोच से बाहर निकलें और अपने आस-पास की चीज़ों को देखें। फोन को बिल्कुल हाथ न लगाएं।" },
  { type: "task", en: "Feel your hand carefully for 30 seconds. It has been there all along, and you have never really felt it.", hi: "अपने हाथ को 30 सेकंड ध्यान से महसूस करें। वह हर वक्त वहीं था, आपने कभी महसूस नहीं किया।" },
  { type: "task", en: "If someone helps you in even a small way today, say “thank you.”", hi: "अगर आज कोई आपकी छोटी सी भी मदद करे, तो उसे “धन्यवाद” कहें।" },
  { type: "thought", en: "After finishing something, pause for 10 seconds and give yourself credit. We miss our own victories.", hi: "कोई काम पूरा करने के बाद 10 सेकंड रुककर उसका श्रेय खुद को दें। हम अपनी जीत भी नहीं देखते।" },
  { type: "task", en: "Laugh for five minutes for no particular reason — at an old memory, a meme, or simply because laughter is good for you.", hi: "5 मिनट बिना वजह हंसें — किसी पुरानी याद, मीम, या बस इसलिए कि हंसना स्वास्थ्य है।" },
  { type: "task", en: "Clean your shoes or tie them properly. Attention to small things is the foundation of big things.", hi: "अपने जूते साफ करें या ठीक से बांधें। छोटी चीज़ों का ध्यान बड़ी चीज़ों की नींव है।" },
  { type: "task", en: "Call the person you have not spoken to in months. Relationships need attention, not just time.", hi: "उस इंसान को फोन करें जिससे महीनों बात नहीं हुई। रिश्ते समय नहीं, ध्यान मांगते हैं।" },
  { type: "task", en: "Eat one meal today without your phone. Taste depends on attention, not just the tongue.", hi: "आज खाना बिना फोन के खाएं। स्वाद सिर्फ जीभ पर नहीं, ध्यान पर भी निर्भर है।" },
  { type: "thought", en: "Throw away the thing you keep only because you think it might be useful later. “Later” rarely arrives.", hi: "उस चीज़ को फेंकें जिसे आप सिर्फ “बाद में काम आएगी” सोचकर रखे हैं। “बाद में” कभी नहीं आता।" },
  { type: "task", en: "Tell someone which one of their habits you like.", hi: "आज किसी को बताएं कि उनकी कौन सी आदत आपको अच्छी लगती है।" },
  { type: "task", en: "Look into the eyes of everyone you speak with today.", hi: "आज आप जिससे भी बात करेंगे, उनकी आँखों में देखते हुए बात करें।" },
  { type: "thought", en: "Ask yourself: what will I do for myself today?", hi: "खुद से पूछें: आज मैं “खुद” के लिए क्या करूंगा?" },
  { type: "thought", en: "Before sleep, thank yourself — and thank the eyes that let you experience this beautiful world.", hi: "सोने से पहले खुद को धन्यवाद बोलें। धन्यवाद उन आँखों को, जो इस खूबसूरत दुनिया को देखने का अनुभव देती हैं।" },
  { type: "task", en: "Set a timer and hold a plank for 60 seconds. A quick way to wake up your core.", hi: "फोन में टाइमर लगाकर सिर्फ 60 सेकंड के लिए प्लैंक पोजीशन में रुकें। कोर को मजबूत करने का क्विक तरीका।" },
  { type: "thought", en: "Ask your phone’s AI assistant the question you hesitate to ask a person.", hi: "अपने फोन के AI assistant से आज वो सवाल पूछें जो आप किसी इंसान से पूछने में झिझकते हैं।" },
  { type: "thought", en: "Silently thank one AI tool — maps, translation, or recommendations — that quietly makes your life easier.", hi: "मैप्स, ट्रांसलेटर, सुझाव — आज उस एक AI tool को मन ही मन धन्यवाद कहें जो चुपचाप आपकी ज़िंदगी आसान बना रहा है।" },
  { type: "task", en: "Ask your phone’s voice assistant: “Teach me a new word.”", hi: "आज अपने फोन के voice assistant से कहें — “मुझे एक नया शब्द सिखाओ।”" },
  { type: "thought", en: "Close your eyes and imagine one day 40 years from now. What would that future you say to you today?", hi: "40 साल बाद का एक दिन आंखें बंद करके सोचें। उस दिन के आप, आज के आप को क्या कहेंगे?" },
  { type: "thought", en: "Where will you be in 2040? Write one line: city, work, and who is beside you.", hi: "2040 में आप कहां होंगे? एक लाइन में लिखें — शहर, काम, और साथ कौन।" },
  { type: "thought", en: "What frightened you as a child? How small does it look now? What might today’s fear look like in 10 years?", hi: "बचपन में आप किस चीज़ से डरते थे? आज वो कितनी छोटी लगती है? तो आज का कोई डर 10 साल बाद कैसा लगेगा?" },
  { type: "thought", en: "Spend one minute remembering someone you would like to spend another day with, but who is no longer here.", hi: "किसी ऐसे इंसान को 1 मिनट याद करें जिसके साथ एक और दिन बिताना चाहेंगे — पर वो अब आपके साथ नहीं है।" },
  { type: "thought", en: "There is something you love but have never told anyone. Tell someone today.", hi: "एक चीज़ जो आपको बहुत पसंद है पर किसी को कभी बताई नहीं — आज किसी को बता दें।" },
  { type: "task", en: "Sit for five minutes doing nothing, without your phone. Just watch what your mind thinks about.", hi: "आज 5 मिनट बिना कुछ करे बैठें, बिना फोन। सिर्फ देखें कि मन क्या-क्या सोचता है।" },
  { type: "task", en: "Call a relative you only speak to during festivals.", hi: "किसी रिश्तेदार को कॉल करें जिससे सिर्फ त्योहारों पर बात होती है।" },
  { type: "task", en: "Give yourself a small gift today — tea, chocolate, a song, or 10 minutes on the balcony.", hi: "आज खुद को एक छोटा तोहफा दें — चाय, चॉकलेट, एक गाना, या 10 मिनट बालकनी में।" },
  { type: "thought", en: "Find an old photo and look at it for 30 seconds. Memories grow sweeter with age.", hi: "पुरानी फोटो निकालें और 30 सेकंड उसे देखें। यादें भी पुरानी होकर मीठी होती हैं।" },
  { type: "task", en: "Listen all the way through to a child or an older person — without interrupting or checking your phone.", hi: "किसी बच्चे या बुज़ुर्ग की बात पूरी सुनें — बिना टोके, बिना फोन देखे।" },
  { type: "task", en: "When was the last time you hugged someone for no reason? Do it today.", hi: "आपने आखिरी बार कब किसी को बिना कारण गले लगाया? आज करें।" },
  { type: "thought", en: "The thing you would keep doing even without money may be your real interest. Notice it.", hi: "जो काम आप बिना पैसे के भी करते रहेंगे — वही आपकी असली रुचि है। उसे पहचानें।" },
  { type: "phenomenon", en: "Look at the sky for one minute. So many stars, so many questions — and us, here. This is extraordinary.", hi: "आज 1 मिनट आकाश की ओर देखें। इतने सितारे, इतने सवाल — और हम यहां। यह कमाल है।" },
  { type: "thought", en: "Ask yourself: am I living for what I want, or for what the world wants?", hi: "आज अपने आप से पूछें: “मैं किसके लिए जी रहा हूं — जो मुझे चाहिए, या जो दुनिया चाहती है?”" },
  { type: "thought", en: "How often do you say yes when your heart says no? Listen to your heart once today.", hi: "आप कितनी बार “हां” बोलते हैं जब दिल “ना” कहता है? आज एक बार दिल की सुनें।" },
  { type: "thought", en: "Look in the mirror and tell yourself one thing you have never told anyone.", hi: "आईने में देखकर खुद से एक बात कहें जो कभी किसी को नहीं कही।" },
  { type: "task", en: "Look closely at one thing for five minutes — a leaf, a wall, a cup. Something new will appear.", hi: "5 मिनट तक एक ही चीज़ को ध्यान से देखें — एक पत्ता, एक दीवार, एक कप। कुछ नया दिखेगा।" },
  { type: "thought", en: "If you could give one year of your life to someone, who would you give it to — and why?", hi: "अगर अपने जीवन का एक साल किसी को दे सकें, किसे देंगे? और क्यों?" },
  { type: "task", en: "Apologize to someone today, even if the thing was small. You may feel lighter.", hi: "आज किसी से माफी मांगें — भले बात छोटी हो। अंदर हल्का लगेगा।" },
  { type: "task", en: "Play a childhood game for five minutes — marbles, carrom, ludo, or skipping rope.", hi: "आज अपने बचपन का एक खेल खेलें — 5 मिनट के लिए। कंचे, कैरम, लूडो, या रस्सी कूद।" },
  { type: "phenomenon", en: "Listen to your heartbeat for one minute. It has been beating without a break — have you ever thanked it?", hi: "1 मिनट अपने दिल की धड़कन सुनें। यह बिना रुके धड़क रहा है — क्या कभी शुक्रिया कहा?" },
  { type: "task", en: "Delete the apps on your phone that you never use. Digital cleaning is cleaning too.", hi: "आज फोन से वे ऐप्स डिलीट करें, जो आप इस्तेमाल नहीं करते। डिजिटल सफाई भी सफाई है।" },
  { type: "task", en: "When someone asks “How are you?”, answer in enough detail that they almost get tired listening.", hi: "किसी के “कैसे हो?” के जवाब में आज इतना विस्तार से बताएं कि वो थक जाए।" },
  { type: "thought", en: "Look at yourself in the mirror for 10 seconds and remember something you are proud of.", hi: "10 सेकंड तक आईने में खुद को देखकर कुछ ऐसा याद करें, जिससे आपको गर्व होता है।" },
  { type: "task", en: "Before sleep, write three things that went well today. The mind searches for what you teach it to see.", hi: "आज सोने से पहले 3 चीज़ें लिखें जो आज अच्छी हुईं। दिमाग वही ढूंढता है जो आप उसे दिखाते हैं।" },
  { type: "thought", en: "Leave behind one old habit today — one that is only a habit, not a need.", hi: "आज एक पुरानी आदत छोड़ें — जो सिर्फ आदत है, ज़रूरत नहीं।" },
  { type: "task", en: "Make one thing today — tea, a drawing, a note, a poem. Making is better than only thinking.", hi: "आज एक चीज़ बनाएं — चाय, चित्र, नोट, कविता। बनाना सोचने से बेहतर है।" },
  { type: "task", en: "Help cook a meal, or try a new recipe.", hi: "आज खाना बनाने में मदद करें, या एक नया recipe try करें।" },
  { type: "task", en: "Look at the sky before sleep and say: “See you tomorrow.”", hi: "सोने से पहले आसमान की ओर देखें और कहें — “कल फिर मिलते हैं।”" },
  { type: "thought", en: "Write one line in your notepad about how today felt.", hi: "आज के दिन के बारे में सिर्फ एक लाइन अपने नोटपैड में लिखें कि आज का दिन कैसा रहा।" },
  { type: "task", en: "When the moment arrives, tell your favourite person what is in your heart. Moments do not always return.", hi: "आज मौका मिलते ही अपने पसंदीदा इंसान को अपने दिल की बात बोल दें। मौके बार-बार नहीं मिलते।" },
  { type: "task", en: "Go somewhere new — even if it is only 500 metres away.", hi: "एक नई जगह जाएं — बस 500 मीटर दूर भी चलेगा।" },
  { type: "task", en: "Dance for 30 seconds to an old favourite song. It is even more fun if someone is watching.", hi: "आज एक पुराने गाने पर 30 सेकंड डांस करें — कोई देख रहा हो तो और मज़ा आएगा।" },
  { type: "task", en: "Give yourself a high-five before bed — for making it through another day.", hi: "सोने से पहले खुद को एक high-five दें — आज भी ज़िंदा रहने के लिए।" }
];